# Generated by Django 2.0 on 2018-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uutiset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aihe', models.CharField(max_length=255)),
                ('uutinen', models.TextField()),
                ('kirjoittaja', models.CharField(max_length=255)),
            ],
        ),
    ]
