# Generated by Django 2.0 on 2018-01-18 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_uutiset_aika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uutiset',
            name='aika',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 17, 40, 17, 453126, tzinfo=utc)),
        ),
    ]
